#!/bin/bash -e

# ways we can be called
# http://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
#
# new-preinst install
# new-preinst install old-version
# new-preinst upgrade old-version
# old-preinst abort-upgrade new-version

NUXEO_CONF="@nuxeo.etc.dir@/nuxeo.conf"

get_conf_var() {

    RET=$(grep -E "^$1\s*=" $NUXEO_CONF | cut -d= -f2- | cut -d# -f1 | tr -d ' ')

}

remove_old_nxhome() {

    if [ -d @nuxeo.home.dir@ ]; then
        rm -rf "@nuxeo.home.dir@"
    fi

}

case "$1" in

    install)
        mkdir -p @nuxeo.data.dir@
        mkdir -p @nuxeo.etc.dir@
        mkdir -p @nuxeo.log.dir@
        mkdir -p @nuxeo.pid.dir@
    ;;

    upgrade)
        remove_old_nxhome
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument" >&2
        exit 1
    ;;

esac

#DEBHELPER#
