#!/bin/bash -ex

absnxhome="@nuxeo.home.dir@"
nxhome=${absnxhome:1}

cat << EOF >> debian/@package.name@/${nxhome}/templates/common/config/distribution.properties

org.nuxeo.distribution.package=deb
EOF

