#!/bin/bash -ex

absnxhome="@nuxeo.home.dir@"
nxhome=${absnxhome:1}

umask 0022

mkdir -p debian/@package.name@/${nxhome}
cp -a distribution/* debian/@package.name@/${nxhome}/

mkdir -p debian/@package.name@/usr/lib/@package.name@/
cp -a static_lib/* debian/@package.name@/usr/lib/@package.name@/

mkdir -p debian/@package.name@/usr/bin
cp -a static_bin/nuxeoctl debian/@package.name@/usr/bin/

