#!/bin/bash -ex

absnxhome="@nuxeo.home.dir@"
nxhome=${absnxhome:1}

mkdir -p debian/@package.name@/${nxhome}
cp -a distribution/* debian/@package.name@/${nxhome}/

mkdir -p debian/@package.name@/usr/lib/@package.name@/
cp -a static_lib/* debian/@package.name@/usr/lib/@package.name@/

