#!/bin/bash -ex

absnxhome="@nuxeo.home.dir@"
nxhome=${absnxhome:1}

pushd debian/@package.name@/${nxhome}/bin

for i in monitorctl.sh nuxeoctl openofficectl pack; do
    if [ -f $i ]; then
        chmod +x $i
    fi
done

popd

chmod +x debian/@package.name@/usr/lib/@package.name@/internal/migrate-from-pre55

